const googleOidcInfomation = {
  metadata: {
    issuer: 'https://accounts.google.com',
    authorization_endpoint: 'https://accounts.google.com/o/oauth2/v2/auth',
    device_authorization_endpoint: 'https://oauth2.googleapis.com/device/code',
    token_endpoint: 'https://oauth2.googleapis.com/token',
    userinfo_endpoint: 'https://openidconnect.googleapis.com/v1/userinfo',
    revocation_endpoint: 'https://oauth2.googleapis.com/revoke',
    jwks_uri: 'https://www.googleapis.com/oauth2/v3/certs',
    response_types_supported: [
      'code',
      'token',
      'id_token',
      'code token',
      'code id_token',
      'token id_token',
      'code token id_token',
      'none',
    ],
    subject_types_supported: ['public'],
    id_token_signing_alg_values_supported: ['RS256'],
    scopes_supported: ['openid', 'email', 'profile'],
    token_endpoint_auth_methods_supported: [
      'client_secret_post',
      'client_secret_basic',
    ],
    claims_supported: [
      'aud',
      'email',
      'email_verified',
      'exp',
      'family_name',
      'given_name',
      'iat',
      'iss',
      'locale',
      'name',
      'picture',
      'sub',
    ],
    code_challenge_methods_supported: ['plain', 'S256'],
    grant_types_supported: [
      'authorization_code',
      'refresh_token',
      'urn:ietf:params:oauth:grant-type:device_code',
      'urn:ietf:params:oauth:grant-type:jwt-bearer',
    ],
  },
  jwks: {
    keys: [
      {
        alg: 'RS256',
        kid: 'caabf6908191616a908a1389220a975b3c0fbca1',
        n: 's0WZ_ZkzbW3vUuUiWy3u2D1RNLWDM02VeuizCFj16xX2Swd2WyS4-m0kLeOBgxU6zhenpzrU4aQypv4YFJMaB2QOvPXrLtcF4re3quSbjxjWqDKc4fJkOYMVV6X6GpaUV6FYdiYNDMiIBctPMoWVSpYhdHulKCXz366BmrAYFqUO1sUYEvkA8RKpnMyiOq85EZFXhTsoBc7OUjXrRGJQh_pUOF49_fZpCCW_y3BA9xDmxfw4AUn9ehwhmZ0J6ZicVNY10Axt7mTpilPtP--rNMYCDRXGODttMSmEJO8bCb5h7hvCM4y9cpsYBR5oq953Ik5Hm24Mub99MwsJGzyp5Q',
        use: 'sig',
        e: 'AQAB',
        kty: 'RSA',
      },
      {
        use: 'sig',
        kid: '209c057d3bdd8c08f2d5739788632673f7c6240f',
        kty: 'RSA',
        alg: 'RS256',
        e: 'AQAB',
        n: '1dODISmOhXR0ANYI5VmtwAGSaMNxgkMA1UkeX4Wngcv8oZFavc2Zht_gibO_SW2MpZ_KeEb0EOaoeiIphi1mvFt9fmXHE0u6g9NicYpEIVBzKserpP-pE5jBCR4QO2u5NWMGOBiu5QEbIii3kt047ml3CqIXiqkmaWogibQ1rtAjeR9CYfp6nwsLazAqJS2t_RprBuGKfTt0zRULH3uGd1GX-9Fh8sNFLI_DIPPOqJVOgviH0EQ38_d1BjuKPISka2FSKqjHfecoB_isfTJVXc5ElWxy3WsVnOE8G-JVIEM5t5UruEPpmGRIc7PCFol-6BS1DJCRiQ43EeW8x6aGiQ',
      },
      {
        use: 'sig',
        n: '21mw5OBuQDYONRNRyek-5Mwe2anpgn-1Ny_RGKU9eNO6_wWg-emzTpwKt4c7dDXgfyJEJ63L0zD_CS-FSyzksHKoGGySsDVX-6nD6n36MGxVCz5Z60wgM5FaSKpf7G3iOJi0IiutLcoYv5jl72g6k6nqrRTe5BSm7JfNedjpRzOeBm3IPQChW9OSW_fufV8q7Ty09ZbS0fU6KRnsMyCi80EYYg0ondJDd56iVUKR4f_OivS-EAZSUzjcu4uWYDzc9lOw8sCbb9oJE4HWLE1bgbQ05jxIqzD-6oztB1Mi-0fT5A8BV26MXnSLVPiTCgbSmQSiTq-I__uqxAfsg2v6OQ',
        kty: 'RSA',
        e: 'AQAB',
        kid: 'e847d9948e8545948fa8157b73e915c567302d4e',
        alg: 'RS256',
      },
    ],
  },
}

export default googleOidcInfomation
